"""Synthetic-only finite-film two-constant Kubelka-Munk calibration tools."""

from .errors import CalibrationError, DatasetValidationError, IdentifiabilityError
from .open_measurement_admission import (
    OpenMeasurementAdmissionError,
    admit_open_measurements,
    load_and_validate_open_selection_dataset,
    verify_open_measurement_admission,
)
from .open_measurement_pack import (
    OpenMeasurementPackError,
    assemble_open_measurement_input,
    prepare_open_measurement_pack,
)
from .open_selection_recipe_solver import (
    OpenSelectionRecipeSolverError,
    solve_open_selection_recipe_candidate,
    verify_open_selection_recipe_candidate,
)
from .acquisition_preflight import (
    AcquisitionPreflightError,
    assemble_acquisition_preflight,
    commit_holdout_custody,
    diagnose_actual_nv_rank,
    prepare_acquisition_package,
    preflight_open_batches,
    preflight_pilot_materials,
    load_verified_open_acquisition_context,
    verify_open_acquisition_projection,
    verify_acquisition_preflight,
)
from .diagnostic import (
    CONVERSION_ROUTES,
    DIAGNOSTIC_SCHEMA_VERSION,
    MASS_SOLIDS_NONVOLATILE_DENSITY,
    TARGET_DEVIATION_STATUS,
    WEIGHING_PLAN_INPUT_SCHEMA_VERSION,
    WEIGHING_PLAN_SCHEMA_VERSION,
    WET_DENSITY_VOLUME_SOLIDS,
    DiagnosticBundle,
    DiagnosticValidationError,
    EvidenceReadyBundle,
    PreflightReport,
    StructuralDiagnosticBundle,
    bind_evidence_record,
    build_actual_weighing_capture_template,
    build_four_card_template,
    build_property_record_template,
    build_weighing_plan_input_template,
    generate_weighing_plan,
    generate_weighing_plan_from_file,
    normalize_diagnostic_csv,
    normalize_diagnostic_json,
    preflight_four_card,
    structural_preflight_four_card,
    validate_structure_from_files,
    verify_evidence_bindings,
    verify_preflight_receipt,
)
from .km import (
    apply_saunderson,
    finite_film_reflectance,
    remove_saunderson,
)
from .pilot import (
    BACKINGS as PILOT_BACKINGS,
    COMPONENT_ORDER,
    DFT_BANDS as PILOT_DFT_BANDS,
    PILOT_CARD_ROSTER,
    PILOT_DESIGN_RECEIPT_SCHEMA_VERSION,
    PILOT_DESIGN_SCHEMA_VERSION,
    POSITIONS as PILOT_POSITIONS,
    PilotValidationError,
    build_pilot_design_template,
    freeze_pilot_design,
    prepare_pilot,
    verify_pilot_design_receipt,
)

__all__ = [
    "CalibrationError",
    "DatasetValidationError",
    "IdentifiabilityError",
    "OpenMeasurementAdmissionError",
    "OpenMeasurementPackError",
    "OpenSelectionRecipeSolverError",
    "admit_open_measurements",
    "prepare_open_measurement_pack",
    "assemble_open_measurement_input",
    "solve_open_selection_recipe_candidate",
    "verify_open_selection_recipe_candidate",
    "verify_open_measurement_admission",
    "load_and_validate_open_selection_dataset",
    "AcquisitionPreflightError",
    "DiagnosticValidationError",
    "DiagnosticBundle",
    "StructuralDiagnosticBundle",
    "EvidenceReadyBundle",
    "PreflightReport",
    "DIAGNOSTIC_SCHEMA_VERSION",
    "WEIGHING_PLAN_INPUT_SCHEMA_VERSION",
    "WEIGHING_PLAN_SCHEMA_VERSION",
    "MASS_SOLIDS_NONVOLATILE_DENSITY",
    "WET_DENSITY_VOLUME_SOLIDS",
    "CONVERSION_ROUTES",
    "TARGET_DEVIATION_STATUS",
    "normalize_diagnostic_csv",
    "normalize_diagnostic_json",
    "preflight_four_card",
    "structural_preflight_four_card",
    "verify_evidence_bindings",
    "verify_preflight_receipt",
    "validate_structure_from_files",
    "bind_evidence_record",
    "build_four_card_template",
    "build_weighing_plan_input_template",
    "build_property_record_template",
    "build_actual_weighing_capture_template",
    "generate_weighing_plan",
    "generate_weighing_plan_from_file",
    "apply_saunderson",
    "finite_film_reflectance",
    "remove_saunderson",
    "PilotValidationError",
    "PILOT_DESIGN_SCHEMA_VERSION",
    "PILOT_DESIGN_RECEIPT_SCHEMA_VERSION",
    "COMPONENT_ORDER",
    "PILOT_CARD_ROSTER",
    "PILOT_BACKINGS",
    "PILOT_POSITIONS",
    "PILOT_DFT_BANDS",
    "build_pilot_design_template",
    "prepare_pilot",
    "prepare_acquisition_package",
    "freeze_pilot_design",
    "verify_pilot_design_receipt",
    "preflight_pilot_materials",
    "load_verified_open_acquisition_context",
    "verify_open_acquisition_projection",
    "preflight_open_batches",
    "commit_holdout_custody",
    "assemble_acquisition_preflight",
    "verify_acquisition_preflight",
    "diagnose_actual_nv_rank",
]
